apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: iot_org
      defaultBucket: iot_data
      tlsSkipVerify: true
    secureJsonData:
      token: iot-admin-token-12345
    isDefault: true

  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: iot_platform
    user: iot_user
    secureJsonData:
      password: iot_password
    jsonData:
      sslmode: disable
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400

